{% set name = "surface-dynamics" %}
{% set version = "0.4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace('-', '_') }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e4f8a41b876382672e63cfdcdd565c53f8c0384d7c65140b0987909967312060

build:
  number: 0
  # SageMath is not packaged for Windows
  skip: true  # [win]
  # SageMath is not packaged for Python 3.8 yet
  skip: true  # [py>=38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    # surface_dynamics.interval_exchanges.iet_family uses C++
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - sagelib
    # surface_dynamics.interval_exchanges.iet_family links against ppl and gmp
    - ppl
    - gmp
  run:
    - python
    - sagelib
    # LattE Integrale is recommended, but it is not packaged yet: https://github.com/conda-forge/staged-recipes/pull/8959

test:
  imports:
    - surface_dynamics

about:
  home: http://www.labri.fr/perso/vdelecro/surface-dynamics/latest/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SageMath package for translation surfaces and related functionality
  description: |
    The surface_dynamics package for SageMath adds functionality related to
    interval exchange transformations, translation surfaces, mapping classes and
    more.
  doc_url: http://www.labri.fr/perso/vdelecro/surface-dynamics/latest/
  dev_url: https://gitlab.com/videlec/surface_dynamics

extra:
  recipe-maintainers:
    - saraedum
    - slel
    - videlec
