{% set name = "surface-dynamics" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 38310ede7df3f855cc76d1f702966a9f8ccc91799de0a57b9dda12a3b68ab1f7

build:
  number: 0
  # SageMath is not packaged for Windows
  skip: true  # [win]
  # Different versions of SageMath have been built for different versions of Python
  # sagelib 8.8 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '8.8' and py not in (38, 39)]
  # sagelib 8.9 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '8.9' and py not in (38, 39)]
  # sagelib 9.0 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '9.0' and py not in (38, 39)]
  # sagelib 9.1 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '9.1' and py not in (38, 39)]
  # sagelib 9.2 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '9.2' and py not in (38, 39)]
  # sagelib 9.3 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '9.3' and py not in (38, 39)]
  # sagelib 9.4 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '9.4' and py not in (38, 39)]
  # sagelib 9.5 is only available for Python 3.8 and 3.9
  skip: true  # [sagelib == '9.5' and py not in (38, 39)]
  # sagelib 9.6 is only available for Python 3.8, 3.9, 3.10
  skip: true  # [sagelib == '9.6' and py not in (38, 39, 310)]
  # sagelib 9.7 is only available for Python 3.8, 3.9, 3.10
  skip: true  # [sagelib == '9.7' and py not in (38, 39, 310)]
  # sagelib 9.8 is only available for Python 3.8, 3.9, 3.10, 3.11
  skip: true  # [sagelib == '9.8' and py not in (38, 39, 310, 311)]
  # sagelib 10.0 is only available for Python 3.8, 3.9, 3.10, 3.11
  skip: true  # [sagelib == '10.0' and py not in (38, 39, 310, 311)]
  # sagelib 10.1 is only available for Python 3.8, 3.9, 3.10, 3.11
  skip: true  # [sagelib == '10.1' and py not in (38, 39, 310, 311)]
  # sagelib 10.2 is only available for Python 3.9, 3.10, 3.11
  skip: true  # [sagelib == '10.2' and py not in (39, 310, 311)]
  # sagelib 10.3 is only available for Python 3.9, 3.10, 3.11
  skip: true  # [sagelib == '10.3' and py not in (39, 310, 311)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # surface_dynamics.interval_exchanges.iet_family uses C++
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    # sage.modular.multiple_zeta.MultizetaValues does not work in sagelib 9.3 with pari 2.13:
    # "invalid flag in zetamultall"
    - pari <2.13  # [ sagelib == '9.3' ]
    - sagelib {{ sagelib }}
    # sagelib<9.2 does not explicitly install libiconv which is needed in lots of places.
    - libiconv
    # surface_dynamics.interval_exchanges.iet_family links against ppl and gmp
    - ppl
    - gmp
  run:
    - python
    - sagelib {{ sagelib }}
    # LattE Integrale is recommended, but it is not packaged yet: https://github.com/conda-forge/staged-recipes/pull/8959
    # sage.modular.multiple_zeta.MultizetaValues does not work in sagelib 9.3 with pari 2.13:
    # "invalid flag in zetamultall"
    - pari <2.13  # [ sagelib == '9.3' ]

test:
  imports:
    - surface_dynamics

about:
  home: https://github.com/flatsurf/surface-dynamics
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SageMath package for translation surfaces and related functionality
  description: |
    The surface_dynamics package for SageMath adds functionality related to
    interval exchange transformations, translation surfaces, mapping classes and
    more.
  doc_url: https://flatsurf.github.io/surface-dynamics/
  dev_url: https://github.com/flatsurf/surface-dynamics

extra:
  recipe-maintainers:
    - saraedum
    - slel
    - videlec
