{% set name = "surface-dynamics" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace('-', '_') }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 09f9be1a19bee60113b2eac2fc583566dec222040e9a9ffd31f1eec022d1e656

build:
  number: 0
  # SageMath is not packaged for Windows
  skip: true  # [win]
  # Different versions of SageMath have been built for different versions of Python
  skip: true  # [(sagelib, py) not in [('8.8', 38), ('8.8', 39), ('8.9', 38), ('8.9', 39), ('9.0', 38), ('9.1', 38), ('9.1', 39), ('9.2', 39), ('9.3', 38), ('9.3', 39), ('9.4', 38), ('9.4', 39), ('9.5', 38), ('9.5', 39), ('9.5', 310), ('9.6', 38), ('9.6', 39), ('9.6', 310), ('9.7', 38), ('9.7', 39), ('9.7', 310), ('9.8', 38), ('9.8', 39), ('9.8', 310), ('9.8', 311), ('10.0', 38), ('10.0', 39), ('10.0', 310), ('10.0', 311), ('10.1', 38), ('10.1', 39), ('10.1', 310), ('10.1', 311), ('10.2', 38), ('10.2', 39), ('10.2', 310), ('10.2', 311)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    # surface_dynamics.interval_exchanges.iet_family uses C++
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # sage.modular.multiple_zeta.MultizetaValues does not work in sagelib 9.3 with pari 2.13:
    # "invalid flag in zetamultall"
    - pari <2.13  # [ sagelib == '9.3' ]
    - sagelib {{ sagelib }}
    # sagelib<9.2 does not explicitly install libiconv which is needed in lots of places.
    - libiconv
    # surface_dynamics.interval_exchanges.iet_family links against ppl and gmp
    - ppl
    - gmp
  run:
    - python
    - sagelib {{ sagelib }}
    # LattE Integrale is recommended, but it is not packaged yet: https://github.com/conda-forge/staged-recipes/pull/8959
    # sage.modular.multiple_zeta.MultizetaValues does not work in sagelib 9.3 with pari 2.13:
    # "invalid flag in zetamultall"
    - pari <2.13  # [ sagelib == '9.3' ]

test:
  imports:
    - surface_dynamics

about:
  home: https://github.com/flatsurf/surface-dynamics
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SageMath package for translation surfaces and related functionality
  description: |
    The surface_dynamics package for SageMath adds functionality related to
    interval exchange transformations, translation surfaces, mapping classes and
    more.
  doc_url: https://flatsurf.github.io/surface-dynamics/
  dev_url: https://github.com/flatsurf/surface-dynamics

extra:
  recipe-maintainers:
    - saraedum
    - slel
    - videlec
