travis:
  secure:
    BINSTAR_TOKEN: gszB6VRNytMXwZhKSdQ1kN4A4C183NqdCAtRIffyEYYIDKn8dKfdJnSi92baY6hZrJq3fEbMWhb9yD5PLhXowgJLgQiFo8/DkfRJ4tmseIqcWNcivsZDmC5EwgByhyJ/tFXfiv5JZQwkGb5REJiiD7aYBB9qxKAGnsxZQkcVK86GG+gGzkClMUlY9SnGLFbrYEnpWW8Lxa6S4F56E2wmXOIwqVsEcTX1WWOcIUEVV0wfdtJGWaqvjX3ehqKipKS5DLbsYWSGnmG3R+kA49JWV9/GNQL94qHjLoCeJ/46T+C4PWuIpAhIacerM3qps0zZ+FQu93JUGuSh+f94HNBMTe+PqJZOoq1n+XR2KdNWEdVz4h8StBN1dgeAfxYLVjwWhZgAh1t6m5bB6RhQ8kWiHblM91CaDTrig7N46TDmvsc4ir19jLRd1c9bYVeBbLCiqc41spek8D/Ep7TZtO9sefqPiTXaiZhoMAOSe4KvAFROwFHBDycu9B7ZUx2POF6Zim+Yx8scp6QLXNT3Qp297D44e3bkXLiL9gBNP5895GW73G25gDvOUi/MmM5gwsu9bLvVftDjnbphNq/8HIM7pwYeDchXTOn9c850II5t/xwffs0ugqzo81VvrIUV7E9B2A9OE7QWhPU0PThHEY/GO84wB60UcF8bOsloXaXrA9U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
