travis:
  secure:
    BINSTAR_TOKEN: Avr99IAHCsUgNe+iEOTh8/R0BjKJeA1vB9LdZFoPlLYhADDco+eqCKTUGH9nIfCO+xeCNyoZZi/a4qCrqVZXdRKeYoDgoIF2w21celpbQIBYg77MbKRu2Pm8HC9eYHHXIW4zuEMf6gsh3HbiQbEtXUGvc8ND0RHZlp15rApONdcopvHXTu0dv8nNMUCy+VYtEYZyQT26qpEhyZHiCRjXDfgrJG4iMqKxwg+GxLJ5Wr4E2IxEinD+PlxrKooU+tvEpyiszGfPARCJ2ThtQuBtDXUBpJT554ckpS1o8tvRGZyYQ7Ga8SWMg06XepwTjKv8X6OkDEZOmOsxJmPYY/2b6PyCZ3oW9Aaz/vFDKV/cvIpVaXrcMhUxGnTL/tfFfKQq7xh+WM4fxIi/HOhFZAzMmeoJm3jILEFBt+U9JtCFDci80hqC4/KQPR+sgiJItXqt/k18b8kgoEEZYHH9FcC8h4wINViAMSpUTS6HsFSMhWz9zPPyUYb05EW4a7hfVV9tRlcxIQKumZbsE4305E2lUVnwblPZCZwL3pyyzVBqUYpmfBYpPPSnT9rFXP8sfgfnAAmryFAxiCgxgYMGG3hoIgFSscHDmid1juv7N2oEp4s3Z4XIn7zM2NZwp2HiJWtIKS55Y0OaqMwLffGwRd124HUqVvRN87Nww409tCpkbxM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
