travis:
  secure:
    BINSTAR_TOKEN: EzZTm5G2bUwJUiHhlLywbcqJbrlyQx/3ukHWR3lmCOPL6BKTPTDly21/RTUa+T463H+YAsRHdvBaIZ8T/WQnVv16ArZ858PcmRgdd/zysBkAfoVEMVvd0FY7OuMyuqZcbT16FBDnSnsXyzf3GD0AymMFK0dfk10AbYi7xfOfO+tMsmH7coQBYRDZ2vTqS0w3c+pApjWvlrj3x5g8FTlTzWrWUMSOkie2xfoU14EUDXTMgfS3n4Zkzu9cHL1Br8yUAjy0A94dFbH+Z5UfBCC21rEim/4uw8xCDbX+rJWaHHUX0L4V10OzSzAicEf87X5M427B2kjm1R34zpfQWlMl7J1ZLa/LxP60oSZnoFlz3MV52VJaCWGed+5ZhwYrSv4hTEvXm3JK98MxEr2hDruSVOWu9cYGdQFTqdmR6a8dnpj/hUderWatDFh0FlieD6Uw9nNw3vDDrrDHZOQmfnh91uHn3966kDnr5j7I3ikRRkdzb5k5HsWbnWx98AtfV/bJ+oeVrLSEX6n0HJuRGs5OkONtjjnPR2l1X/uqv3QQdfoY2KkTsZ29hXC5gBOWBUD6ZCn+4h+DhwLjJ73tbW2MgaQ4pgj7kfQZafSy5eetar/uoT5me2s+OuBSH9W+HDSzKzHWUN4wTdvGkBEdUEWulty+GttV+2IuiLLkW+RcWwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
