travis:
  secure:
    BINSTAR_TOKEN: a356hU6heOTmSk0nunIMhv/NuMhmQA65lCtclgykBI7zqOgasRtydcJsTdKjtVC2FgCmNQupLypHEtC5Q8jRxD8CL/+gOa6cATAAgbMMwyXnaHukTODfGSEq5QktkfYHLgut9/Ud4y4ELcbKz3IFmdqCQ1+k8J1DtALjIiQ4F+HYHRs/eupXt4SvbmdYK4kj01Fh8daI2rkk8RY78Fv9ri7nlWVbs051y7DPEel1PFMX5o7wb0tPqCp+0akgiw4KfkdbiUv/wo/5qQdFlXTD44PvoNht3kNnHGfuRyv0BMEHjWxvzAQjcLFBDth+1C5ctcKhxWvPIp+Ni9ZaZ65JwVuv1n4CAQ1W4mw8JLtpFmQN/TUqHrlLtPMivemSaZyPxZPGN8UMuf6+42mdTLBr5WGVqd5HnmXdJPK6O/p5koZ8i53P1aLBoGNRsUUtve8MzkqM9owVSq8c0UwqncG+GBftfJBp23t4X3r2Ie882/Nlj2dBmYDuYwHS061b49kKLl4OfYvBth473nJ05EStoWZkrTlYyVR+chcj8gGJNA3vOGOHE3AW8bHSAIqcZyVs4lp6x7zCy2cqQUKhoSlwHLDe4mticqiYldzX4aEFPbrVsqx3QY4KqBxHIyYngRinmythmbj4BcpnN/TW3WupY5xJzdOjsGqXJ1yQinc8z4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
