travis:
  secure:
    BINSTAR_TOKEN: KALR0Cv66SDos9g+RRwm6y3auIsg13Xy8kowJKPjA2ghmZTaUdvt+OeOHMrpO+DqEV/cxzkgHwrN3cgmdm6F2m+Jkp9j4UCumvKXfPRlv5iWKKvHHbX5aYMDcb+gIDxZnIo+dkIINFzBHcdycm91jb8voKowUbIUqOhwwUW8MaIpzyUPUT37mMKPoXatWr9YXPFLdhZJzDsKft4ZLDq7nKlOKu/npz/c0JEDMOUvDMLHblj88izjyOzSeDcL+wfzoJmKx3k0tF1L0r/b/xJP3elxykMNcWTFhIUoDXYeGjjyZpaNSfvqHRuZstpfcNZYZOwSvBhiL1ZCoUEb61JaW5O7xwCEagpFyT2J/LYYMy+JV2af8IJFIqOlVZovkpshTiEku/1pnsNDaHu10t9kRU6C6dBdfa0iZaKOfiOjxjzuwdsEZDtq7JuJLbgnw95fOxlIPnuwHQPhqKo1BOqbtKavaEs1xutSv4i79ivX8liMWndbWwP7HbPMgNjemn9GkVr2j3hwBTQRwCVflAX5PVQYwM4fasE90wNzh9gbrWj9l6mVs4y1/TBanxAa95WkeS5B7XjBXzpQb9uTtUEsyLqniQtWuXq0bp2nq/4LbS+MyD8RTj7zueTGmjhJ42yFroy1gLDT34FE+bnHDJK/RejJTTgY3YmX1Y5BAozGEms=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
