travis:
  secure:
    BINSTAR_TOKEN: MCJSjHqaY9RhiQfh7Ncu79nW8QRmUzA65g9fEsO+Td57L44/7/iXFSa8VS3UeFEkBjqbMlxykc/ZBIJSN4N0uIyZz/ODWV1NjrlXVrmX+upK/SCr/PapGM8kdGF7IPo19p1zzDrNJvSXt+tv7OKBTKIo3EQ1WAH1ifQZp0GeDMI2OkkdePIoIyLTwu0qJyMhHVMSAxF5YZf2pXrH/F8AuEhrCd4ioUje21AdGMjBKtRngexqNOF01lYalAGIxNby3BALen170MzCfYaGh2+vXxBtySJ/mp/7MZFMuazAAkoAGIVEa9LqKA6yiwOmUrZPqSlQMqvbXaUdvuWspDVAlJ4ePH2RRHXyXfeosbXxz/tYpqBGVbvtaWN92UR518wDoAVx7FMYGgK5Ir3uGpYbjUQlVpxCbC8skTni7tRpDvVtaRO59VaeuKieTaIQhXGdPa62lq99olrqHCbzEgTxFlT9906YH5J1TbN+T0vJRfqolxvxweb66hDLGb4/uB35eGmwRGTQWMWE1/O94Gk6ur3t+Nopsfw8ZAk+u6QsjF0b4r4I1Z4ZDlbKE54f0xeXCrCHG8BLK+xAeqNNcWP9z9RYk4UDwyT/21r/5QpQDUNKFLy9DyvZ784VKkigvVeLqGHb6Vz9guEueUNlIXsNfdd5E0fHsas1SN33FGgRQtc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
