travis:
  secure:
    BINSTAR_TOKEN: MyORdymaSERWEYKZSld5fXaPX6rSep33KHCgLvcgCfhAv2Uq6wZrNkvBBfCBqXJ+Fc4uWyfCE6xSp62YZZtbUndI/LC65+zvleLXo5NycI/xnN91pFoeZ/g/JRVhwnODxpfa4BED7KmHNKGRIy82ajV28NHKTUeIxFViaNewEZ2n5mHdYqvAVsafimB5v4Nb7lFwTHeOVFUUkqFqX3xmh8TdaVo0L84GcTf6zcU8XV0Y3CRawRNOAqqh81HLpkccCGVkoUmjsNNPOCsPVhCS5gG9yf5lZKvwAtufCotmrHRoaltpFhMNhSkv5xVFTy9E6H9EkkEGw51Dd532SOe6XnlRK/sg860wPsqCHHXe0x0esvTEwVMtcABYsYT3XQv2PmhfTdk8rO3CLnOZYtdUZIVebSE+prmIXDtGvnm+dot8zDOeWhcoQeI37g0qXzSIVthcB6Myim0Xqjq6JahZQ5Z2Bj+qXCknSqMwwmn1NuoZJXat8sKbeCyXB0AVIslhO0aM8Zxhw3i9fSQwF0PHZxP617qpIJYmA33VNWchkAzvSNUBXDBoRHuE1eOwTY8njhM0WghV7mVtEJA+SXh22W+7f/z/Av6p00dyPh4kA6M3gzabxBeDTLVZectMlimMoQwFlFtg/kbGEIuOj4I9z9BMFkD6IVjWqwlTldvT6YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
