travis:
  secure:
    BINSTAR_TOKEN: NTFEYQwhXUt5ZiOW7gsON9QWquballsLVJAHnTiOeDO8R8g9E2mwNRAtFfG7AsRwYRmBE8q25i8+Kkb3C54Zr/MmNvDUdsmuxXnTUfh9u+OX48kLpINW1s0FWBhMD1BAcdJUGc2EnjxUqg++jtFADw7U2RhDECnJt+TV7Yq9IY51xit/We+meGh6e/ERu7WIgsW8EpB63WY8HzaE9nKMI1/7Y2uiKAD0/f4gQN881hx7UkLTpao18LcRzk/0eRmW3ASlkxGthfFtABR4yhwx5rnRmkZHiJtxUqFVk0yMWOveGkxgBEwLHnnn8vjpJSTE+KAx5Fx29L46SiwYearF5hdE98mcmKTniNZu2NZcASLv9X9C4QA4f1HjsY9L2YC/xAKr2GdXKGNyOuEAQxKkHGXIKqadSu1K0qziScZ5+QhHgN6lgfT2jxMbt3TJZO8P+x16XrmF9mYy/izoA+LUToXW7pRxybNJDSUvanJLHOkIbihCtvBejGhGvWDlXfApot47zMquCKHkCyFCZiUeUA9Uwr7TRNvlAJW6jCMvWsCN92866qS8hX/ucmCC+1/3J7L5YFA+TKdI9RozVbGZhuRTPwgNBJIRSlwY28r1r5vsruPBnOgl3Re/iyI/1HxFkEseVxUnXXrr55pPsy0YCzd4d5OPHYM8hrx9tVSqTlk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
