travis:
  secure:
    BINSTAR_TOKEN: FVODDNe6RPpu+P3MIG7f+gfeXCEh0832NyqwERdw0FEDTrcgxjBCDUL3Scm7SP110U4xeX3WHR15eVfvLDStQPd49K4pbAkaR9sb6BqQp26Af0hAFzzoPDP58IOFQvFu5g6Ln7GwxjiqLgfuTPA3PGn4ULR+WnSr795vAfosySI3TsGR/5FRg9lgzXRDyqJDmpTmI5UQ0bNa8c40HlyiSuDmJybXK1qNgiEoNuK2zb5TA8vgyEQguLZ7sH20hQxyrFmrIg+xy1LiHptQ6RjmKY9YSlcRiFzIehhCg953WzH1oh2GJN767ixViJ8hI7nm/9qYcL7HgpbMIMsjWaafSD+m6NIsk3SsIjwv34Pzz+gVbkTzJqOlxLMEgLhRc9IDr8dyet29t2doI7LPKhwpJPlj1m57IERc2d6jTjzP/xtewAPQNZa/ystwdqWMJRGRTwXGqw1SRgeMoL1Wg2VgBFn5zydZl/tlMtYBap9Tdrl9aPJ6tXGHISdAPWlmQjriRcCKrygvyRZd7Irap3TGtgoX3yqILZo+Twnii4JAVKv1qRpWFCAOy4GkuNUrTpPeeNVbSsBhf/acHqGaR9z5HEgXNsholw7JX9unBS3zQkbJcgleod/1kR2Pk+cw2nyPb8Rg1280uCT2ze5Hd1iGZyU7v9nlGAk6MAyKM6kW9ow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
