travis:
  secure:
    BINSTAR_TOKEN: Z1MbnIRazQX6AfHB505C9YOD0rf7Zb2MHlu2clSCw0YJnzBLGNU7kbaOAuYxf3eShyeV6zOScVjtiltIBAeY/ZWBEpsEYESG24Brj/Wl0/50nh39g6xeXgW2GVA5TKzR7C0pVTAWNWgf4h5qnhBGBTsNAH48wunPZ05zsckt4CWZhWthpH3Fjv/m7dPz6buRq3TwvpP40Ee6ruArLhPqiG5Yvs4FMdqQvaRKl04SZrbjsZoUUM2BPupM5fyPiH5z0HffEWBBUt8iuYiuHWUG4cRM6ptf7dAqHYYlL/w69fCDQnyeFitk/Dfg5se590f5qH/qhkEwG1RB+bK7xJTIxtX4y37bp5UKvZ3nD1ugZAr7Y47CiX1oQZmY4/RIJckYXxmYyyhSnnIFIgYdhAwlHFZQxqi6s2qV14O75FzGeJ05KCMoqGEzgbxWmKXa083Nrfr+aID9lFjfIxwSNqhVjwOG7V5rh2MmGCkNe9gIg1/b4lRwivdaC2MVgLXPkJiOW/ubWL9tMczbKa+bHnbu8pkmEUtnW63SM1U0F4r7Mx1pBuG6ahM14EeBWxU9GsDmhN0xl7cMjQBx2P+FtV3T9obeVOp1H9F9QbIzfGF46Srkq4PKgRxp2Cl22dyHkDKCwldU5ZxJ59znR5qnEEH/0X7hAehsCcrFkpYaEp/HnjU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
