travis:
  secure:
    BINSTAR_TOKEN: JTdP8bkNh6Nn0lhjJiDIFi8Zs6PeQDjnpIS+UuXDo+7dMLPNWr7VWK0Zpu/x8cRxDXFjPmcFkOUC7VjdANgjgqkmngSAUP+QLX7ZD9t8seM2sQXLPI9pEpjCq+DAVMOf25xtI7FA6buea+F918TaFR14sJxGkgJtMt7n/EtAsxEcp8exwixFCCof/bZTR9yh9/CZSXUtubEU8fOrVqW/wBh1wgulaCyfBCneE6LpsMzxH7k9YpGPd1lwfZA0aAOk9sjWWK4dWFHVhO8GWRCUufZSGuIQYoa+iySR5XXiwX9CAj2oAgjQYvUZkbdKMIOkBU76fivY6YEx0/y2alzfoA8jOTe4JnW04bp6+Z5MtBOIknFTiSudsywhI7yEWO5c3TRkwuLVxx1LCW92Us1xdHfppSca9jQ9DXU5cu/hEE8nPAObbKXdhNBh6y+S6UlAF8mNcjYuopd9S2zfAYgxD7LhkQc3VO2fBr7WKgKhuofYbP5QvUxiCrvfuUQA4Csbxg7hphr6KJXpx6qdpRZyni7eYBrdenIX85JVIVfRukQEuANSTpa7+RFcW7Az0qdZw054vTS7/ynxTXlah4mGccE8JLyYZwymHzngM6GAZ0VMLXgifww9ZA+rKYPa8lJT0bTt5FDYiyV3jX1gBedE8mhm1judgryoP3ykeRAM+H0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
