travis:
  secure:
    BINSTAR_TOKEN: D9/7R4E9hbu+YlRqedQynPUl4/+7KeimkVw7JkXgifTzia1bReP5yUn8imcHTGNqn8DQ4w47xZPMIgCpphnUR3UMd5fc0T3tAv6frv4AbIExN3zujnHqahAc//5TiZi7JwWDRixoKpkkeLISyFYxewAeds21JNRHGiZBmFRDPKwOPlmvmFtlHbr01VG3uTLnmUEfI3xWF6fnrEVmsWF/2H0iUIrVWXbbeMUR4e/cyPgiDXe7sGsMkBHZAklRZv0lmZzdjn6s7cCrBVqtNNplb+Yc7/KgU2Pk8xpdK2a7C4PY2ne5jkzHRqbWwYTvAhw3y32/JsFpEkIxJWszXoYNWwNEZYQASNq+N/Jsa0e4MSCJb4oHe/cjCfF4qYWi/ngKXJtUcAY9yDmjGDLDZbb18MQW0m31dpqvpxpP7RsH5k3lYXhwu7uMxVWTp9So/K+PBnit7CkfmEiytWA2CExal9AMaphIvw7OtNc06VpeGkpidayPOqMgRTG7IoATz8rbfksmwZC1PyxsaB7WVXN2hDm5DEFijfUnc9rGhnO5NlGa0jhgMp8eSjhoIrTLPtqq0XcS/DW+6Nxa5/qjyaEPdtD75UvePr4ucm2EPqeKBzIq5eckvib2/4uFryGd2xjl+4yp0oXLqmmh/ZCo+ge41ZubPi/bhrClM25qQV237XU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
