travis:
  secure:
    BINSTAR_TOKEN: XS77gHyGnl6gQXVf6pJwK/wluuetQLtnRu+LgYiOGaydExlgPigQBM/DgrteCxe0kDmdeS5ehSzxEH1mMoIrLKgNtV1Nb1Z+7LNb9ZKJvbPROG5rUUcao1LjAID/N86FwEisjsDXq5CjxrCXLkiF01aMO7vzgFBWyTyPcZVJ0ShaDIaSqOlj19kAz/abKdi1FydsiJg8r9AOevhuPV1A6DByl3aYHrH/xYh5x9P6glNjCCgXCfFcwbZLBQNbZDOOkRk+/LvW64YuJZHe2RkB5M+UcbevbE2ppKHYEp9iNHj4laHrC0Ij6jQZcbS9nVunaQfCDg7AQaAHibCTpzGD78RjvEQJMK8DenKyRk7hPfSfc31/Tds2BjAuNXMrOpglovwMdndvI9XV0s1ZIdT/6F+yjAJ7grc3f0NRZFsRpXXUVUPyh4gQq6Hs4bqahW76EiDkdOoG5iuKPfMFQOBpq0friMshJvAX4kVGdGXqojhCHoWgVIBJ1k39U4EE48h+wuVd4F5hOfzW/TWXpXwkEhzV+qj1gnmxIcSr4XqhMKPQDHoV3r4HcIqSMNCE1CSu5oZWliRVyb9AsCuWRRH1xgmVxu1dle0q0K0NmlGjsj/VYO8peUxIouC//pxXGxG16cGQEg47TQ61ibYtRWIg3n+t3irDc2xCwy2EWyLcdr8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
