travis:
  secure:
    BINSTAR_TOKEN: Z/No6hqDC4TWCMoe7ZNz18bbUaPJ8nwblmbv4DtOjlc9LBsr7mudvaHXXSAculiNLTFt4RWdchuR8L5asb55yARPYz3+gO8RtFtFDcEpOB9PfpDFxVAHl/5sMVaNtaNCiO3OPtiKt0vmcRGO9BC5uc6wJWRZYzSUWNK/F4BmSbF/017XPpCOCErcP8ZTx7dH2M+fRR2ulsyLuyjSnGmMDzWD5h+UeFsI926iDBLVqdkqIk4FhURWcXkYZviD21B2UPhaVQacsmpe1NJ/nGVMU/oPVKtup06GQUQs7WutccUMQPf/0f1HvuQpTo1ivZwPvlTJERb6ymRg9ryfwxxNsHN+cjEhIYs992spCho6HxlUATzkNDz0rvmKACDhgW48wexdqm1aQtABEhjtMe0xXvTHYkftu2HlPZpJYMgarlXJcMOqM3S0/kdsNSchxz+BgMqzUsl+t/73EtBDqmMnKmFD2VEpFXSZiX05znydQv7eSAtHwZN5x8u3GmVmMIByAHYq52FfNfBok9JfjAeshOoYG256kjwl6lPc7SlJzASYpZQCxmDziisY65XPkwgomsvOfNA5wqt5OH42e72t7Ickk/BHWWhTJI4K/CbNWJdFp6luSnDFw8Q1uQg7oaTVDtyrCXW6r6EUaYJLMGT/tQ6fAEAxaHEvd+J3ifohMI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
