travis:
  secure:
    BINSTAR_TOKEN: A1rFKGPs9SlsGWmSPyRrC00rYAnLOyQAIt25aAAvpn22P0az5a+NdCiJw/GZhHczVmks3SB0UZ1IzTS9tEUtOMJqs4jZYjPlXLlLH7dqaXVV0yXx7TveD26xeSNOlTAdz4d/sloY7NEOLoSh7XjIQnaYdBy6eL9avQV92hajQa9KAQT+a6dkLhAwGunR/pGTuahQ4mZDXBJ+nZsHXFmHlc1NX1zTc7jJPCJG5EI8S7fwkz7LRAcYtg7lcedIzwGvMM4iE/xR/ebC/HsQ8y54EhIwU3/Y3nzyU/2bRwhdf4IP8ihFhu1Nj23au7W1r/LA+SsctT3wvgRk7QPXc0+0xOfb5GIS8tbfDO2VPy7KHbAGzJxhHmEOCro3koVyTWVHtRDh6GKy/Ud2Gjsta66/3Xqh5GFbmCyH4PFDuPSsWF1ftIB/Sz3FkrCssg+RuSjPrSmmyAC/TzkelYBtF5+MRJVL9nh+OXYfMc6PkJAoDuVVZe+/Ng7z7oPd4uCRbwhvGf4w10iltGXclSZf6nLNk/yoyP3yL2qM/2T/nvmQyXP0heiHLbqldF9FUoVhZL9WNoo/SzDNyjzFcd3Wo2RzSXt3wDXdKMV3yDkLKkGRFMJEHSu3foCpVmz5If+4QWasnlnhCKbIAYjAw0mrPCJyty8iFtijZWwQur4eOOEgXPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
