travis:
  secure:
    BINSTAR_TOKEN: H3crI/MU73n/9btnRpyvQVdiT/Um8CcUkgyQO765i44uIuDC0JiKpfVxTdJ9EMoELDmQ7CvoF+yIEcfTzXx5SzeNnwSGbJDtUydKgeMoxE82CLcd2ryR91KSEtCBErTag986La4DyXGcWlqiX5SzRGlb2XnSc1Gh0G7/K1p6NRyrxL5x41CcBLFD38zItBruWeLq+wx2F97tgfPavQVrPnNR3VAKwI8K1uL6zGBeIb5dWwlNYgSk4gfs1NziFXgRDNABoZdhEnBM07t9ZsQ/13pHaJiF7BUixRKj7TacFPUHO4uKF6arvTTcC0pYvOODo1w3QvW/FxZFTKxmdjEkuFQDiWP+mogr+t8lgKwTSzTzt2RkyeX0vwQBQh7MTv3RDY2aW9deau6yfBTNifPEl5rXbc3gZjPAh+nI4Zl5CTBpxA8nFr8hUhcgLqvZ7bi9H/2ijwSKteu7MlFcqdiQan2ycrhq36AMiOPFT8/tO7G9r1xf5F0hSi3EEFvrzj+FCJOBA/3jvFWe9+l3j1Po9+x+2cqOVqaYqnDHcEp0NM2y6iVbvDF7LQKbJoDIvffylt23DnNOnj8kScs5ALqbIbyqixtx+wvoNqvKRcYB+NQWjvLsbmjKxuI97tRrSxpjTDJLD+8giFte0+w5CG567fUkAAY3i19Rha/vAkefOXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
